boot0:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  base_body_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_body
    pid: {p: 500.0, i: 0.01, d: 10.0}
  body_arm_position_controller:
    type: effort_controllers/JointPositionController
    joint: body_arm
    pid: {p: 500.0, i: 0.01, d: 10.0}
  arm_blad_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_blad
    pid: {p: 100.0, i: 0.01, d: 10.0}
