#!/bin/bash
#   Ad hoc script to build opensim from source
#   Part 2: get all dependencies
set -e

BUILD_TYPE="Release"
MOCO="ON"
TESTING="OFF"
NUM_JOBS=8

# Install dependencies from package manager.
echo "LOG: INSTALLING DEPENDENCIES..."
sudo apt-get update && sudo apt-get install --yes build-essential cmake autotools-dev autoconf pkg-config automake libopenblas-dev liblapack-dev freeglut3-dev libxi-dev libxmu-dev doxygen python3 python3-dev python3-numpy python3-setuptools git libssl-dev libpcre2-dev libtool gfortran ninja-build patchelf || ( echo "Installation of dependencies using apt-get failed." && exit )

#  swig moet versie 4.1.1 zijn.  (installed from source)

# change this for a different location
OPENSIM_DIR=/home/sietse/Software/OpenSim
cd ${OPENSIM_DIR}

if [ ! -d build ]
then
    mkdir build build_deps build_core build_simbody
fi

# We first build simbody, outside of opensim to make patching/rebuilding it easier.
export SIMBODY_HOME=/usr/local

cd build_simbody
cmake ../simbody -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_TESTING=${TESTING}
make -j$NUN_JOBS
sudo make install

cd ${OPENSIM_DIR}/build_deps
cmake ../opensim-core/dependencies -DCMAKE_INSTALL_PREFIX=${OPENSIM_DIR}/opensim_dependencies_install  -DSUPERBUILD_ezc3d=ON -DOPENSIM_WITH_TROPTER=$MOCO -DOPENSIM_WITH_CASADI=$MOCO -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DSUPERBUILD_simbody=OFF
cmake . -LAH
cmake --build . --config Release -j$NUM_JOBS

echo ==== done  getdeps ====

