#!/bin/bash
#   Ad hoc script to build opensim from source
#   Part 3: compile it all
set -e

TESTING="ON"

# change this for a different location
OPENSIM_DIR=/home/sietse/Software/OpenSim
cd ${OPENSIM_DIR}

# test for previous install?
if [ -d ${OPENSIM_DIR}/opensim ]
then
    echo "Directory ${OPENSIM_DIR}/opensim exists on your filesystem."
    echo "   Consider removing it before continuing."
    #exit 1
fi

# We first build simbody, outside of opensim to make patching/rebuilding it easier.
export SIMBODY_HOME=/usr/local

cd ${OPENSIM_DIR}/build
cmake  ../opensim-gui -DCMAKE_PREFIX_PATH=${OPENSIM_DIR}/opensim-core-install -DANT_ARGS="-Dnbplatform.default.netbeans.dest.dir=/usr/local/netbeans-13/netbeans;-Dnbplatform.default.harness.dir=/usr/local/netbeans-13/netbeans/harness" -DBUILD_TESTING=${TESTING}
make CopyOpenSimCore
echo ================= Nu PrepareInstaller
make PrepareInstaller

cd ${OPENSIM_DIR}
tar xf opensim-gui/Gui/opensim/dist/OpenSim-4.*
chmod 755 opensim/bin/*

# ad hoc  nog nodig?
#pushd opensim/sdk/lib
#ln -s libadolc.so.2.1.0 libadolc.so.2
#cp ../../../opensim_dependencies_install/ipopt/lib/libipopt.so.1.10.8 .
#ln -s libipopt.so.1.10.8 libipopt.so.1
#popd

echo ==== done  ====

