#!/bin/bash
#   Ad hoc script to build opensim from source
#   part 1: get the sources
set -e

# change this for a different location
OPENSIM_DIR=/home/sietse/Software/OpenSim
cd ${OPENSIM_DIR}

echo ======
echo  New files can be copied
echo  Existing files have to be checked for changes!
echo ======

exit 0
# de vraag is of dit goed gaat!

if [ -d Patches-opensim ]
then
    # Add patches
    cp -r Patches-opensim/opensim-core .
    cp -r Patches-opensim/simbody .
fi


